workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.10


stages:
  - test


before_script:
    - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy app
    - mypy tests

black:
  stage: test
  script:
    - black --diff --check app/
    - black --diff --check tests/

isort:
  stage: test
  script:
    - isort --check-only app/
    - isort --check-only tests/

flask8:
  stage: test
  script:
    - flake8 app/
    - flake8 tests/

