FROM nginx

RUN apt-get update && apt-get install -y netcat-openbsd


COPY ./static /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY wait-for-backend.sh /usr/bin/wait-for-backend.sh
RUN chmod +x /usr/bin/wait-for-backend.sh

COPY start-nginx.sh /usr/bin/start-nginx.sh
RUN chmod +x /usr/bin/start-nginx.sh

CMD ["/usr/bin/start-nginx.sh"]